---
- hosts: web
  name: Install EPEL on the servers
  become: yes

  roles:
    - geerlingguy.repo-epel

- hosts: node1
  name: Install Apache on node1
  become: yes

  roles:
  - role: jdauphant.ssl-certs
    ssl_certs_path: "/etc/ssl"
    ssl_certs_country: "US"
    ssl_certs_locality: "Eden Prairie"
    ssl_certs_organization: "HTC"
    ssl_certs_state: "Minnesota"
    ssl_certs_common_name: "htc.local"
    ssl_certs_path_owner: "apache"
    ssl_certs_path_group: "apache"
  - apache-node1

- hosts: node2
  name: Install Apache on node2
  become: yes

  roles:
  - apache-node2
