---
- hosts: redis
  name: Basic install of Redis using Yum
  become: yes

  tasks:
  - name: Install EPEL
    yum: name=https://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm state=present

  - name: Install packages
    yum: name={{ item }} state=present
    with_items: redis

  - name: Start and enable httpd
    service: name=redis enabled=yes state=started
