---
- hosts: redis
  name: Basic install of Redis building from source.
  become: yes

  tasks:
  - name: Install EPEL
    yum: name=https://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm state=present

  - name: Install packages
    yum: name={{ item }} state=present
    with_items:
     - "@Development tools"
     - python-pip
     - unzip

  - name: Install pexpect with python-pip
    pip: name=pexpect state=latest

  - name: Create a src directory
    file: path={{ item }} state=directory
    with_items:
      - /usr/src

  - name: Download the Redis Source tarball to the src directory.
    get_url:
      url: http://download.redis.io/releases/redis-3.2.5.tar.gz
      dest: /usr/src/redis-3.2.5.tar.gz
      mode: 0644

  - name: Unarchive the Redis Source tarball in the src directory.
    unarchive:
      src: /usr/src/redis-3.2.5.tar.gz
      dest: /usr/src/
      remote_src: yes

  - name: Run the make command for the Redis Source.
    shell: make MALLOC=libc
    args:
      chdir: /usr/src/redis-3.2.5

  - name: Run the make install command for the Redis Source
    shell: make install
    args:
      chdir: /usr/src/redis-3.2.5

  - name: Replace the command line in the install_server script.
    replace: dest=/usr/src/redis-3.2.5/utils/install_server.sh regexp='\`command -v redis-server\`' replace='\"/usr/local/bin/redis-server\"'

  - name: Use the install script to create the basic files.
    shell: ./install_server.sh
    args:
      chdir: /usr/src/redis-3.2.5/utils
