---
- hosts: redis
  name: Basic install of Redis using Yum
  become: yes

  tasks:
  - name: Install packages
    yum: name={{ item }} state=present
    with_items: 
     - "@Development tools"
     - unzip

  - name: Create a src directory
    file: path={{ item }} state=directory
    with_items:
      - /usr/src
      - /usr/src/redis-3.2.5

  - name: Download the Redis Source tarball to the src directory.
    get_url:
      url: http://download.redis.io/releases/redis-3.2.5.tar.gz
      dest: /usr/src/redis-3.2.5.tar.gz
      mode: 0644

  - name: Unarchive the Redis Source tarball in the src directory.
    unarchive:
      src=/usr/src/redis-3.2.5.tar.gz
      dest=/usr/src/
      remote_src=yes
