---
- hosts: redis
  name: Basic install of Redis building from source.
  become: yes

  tasks:
  - name: Install packages
    yum: name={{ item }} state=present
    with_items:
     - "@Development tools"
     - pexpect
     - unzip

  - name: Create a src directory
    file: path={{ item }} state=directory
    with_items:
      - /usr/src

  - name: Download the Redis Source tarball to the src directory.
    get_url:
      url: http://download.redis.io/releases/redis-3.2.5.tar.gz
      dest: /usr/src/redis-3.2.5.tar.gz
      mode: 0644

  - name: Unarchive the Redis Source tarball in the src directory.
    unarchive:
      src: /usr/src/redis-3.2.5.tar.gz
      dest: /usr/src/
      remote_src: yes

  - name: Run the make command for the Redis Source.
    shell: make MALLOC=libc
    args:
      chdir: /usr/src/redis-3.2.5

  - name: Run the make install command for the Redis Source
    shell: make install
    args:
      chdir: /usr/src/redis-3.2.5

  - name: Use the install script to create the basic files.
    expect: ./install_server.sh chdir=/usr/src/redis-3.2.5/utils
    responses:
      (?i)port: 6379
      (?i)config: "/etc/redis/6379.conf"
      (?i)log: "/var/log/redis_6379.log"
      (?i)data: "/var/lib/redis/6379"
      (?i)executable: "/usr/local/bin/redis-server"
