---
- hosts: redis
  name: Basic install of Redis building from source.
  become: yes

  tasks:
  - name: Install packages
    yum: name={{ item }} state=present
    with_items:
     - "@Development tools"
     - unzip

  - name: Create a src directory
    file: path={{ item }} state=directory
    with_items:
      - /usr/src

  - name: Download the Redis Source tarball to the src directory.
    get_url:
      url: http://download.redis.io/releases/redis-3.2.5.tar.gz
      dest: /usr/src/redis-3.2.5.tar.gz
      mode: 0644

  - name: Unarchive the Redis Source tarball in the src directory.
    unarchive:
      src: /usr/src/redis-3.2.5.tar.gz
      dest: /usr/src/
      remote_src: yes

  - name: Run the make command for the Redis Source.
    shell: make MALLOC=libc
    args:
      chdir: /usr/src/redis-3.2.5

  - name: Run the make install command for the Redis Source
    shell: make install
    args:
      chdir: /usr/src/redis-3.2.5

  - name: Use the install script to create the basic files.
    shell: install_server.sh
    environment:
      REDIS_PORT: 6379
      REDIS_CONFIG_FILE: /etc/redis/6379.conf
      REDIS_LOG_FILE: /var/log/redis_6379.log
      REDIS_DATA_DIR: /var/lib/redis/6379
      REDIS_EXECUTABLE: /usr/local/bin/redis-server
    args:
      chdir: /usr/src/redis-3.2.5/utils
